spring.application.name=serviceflow-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/serviceflow_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.placeholders.admin_password_hash=${ADMIN_PASSWORD_HASH:$2b$10$2Xha.zPt8U1j2DgxnUOW/Omqp1Z5gA9yjqWUk/etB9wa9kSyYiRS2}
